# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170101_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agree_on_terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='want_to_receive_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
