# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170101_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agree_on_terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='want_to_receive_newsletter',
        ),
    ]
